TEXT_COLOR = (200, 200, 200)
TEXT_SIZE = 2
TEXT_THICKNESS = 7
FPS = 25
DURATION = 2.0
NUM_FRAMES = int(FPS * DURATION)
TEMP_PATH = 'assets/temp_preview.mp4'
BACKGROUND_PATH = 'assets/comics-background.jpg'
OVERLAY_PATH = 'assets/comics-overlay.png'